name: 'Test Monorepo package split'

on: 
    push:
        branches:
            - main
        tags:
            - "*"
jobs: 
    packages_split:
      runs-on: ubuntu-latest

      strategy:
        fail-fast: false
        matrix:
            package:
                    - local_path: 'src'
                      split_repository: 'rs-multi-global'
                      

      steps:
            -   uses: actions/checkout@v3
            #no tag
            -
                if: "!startsWith(github.ref, 'refs/tags/')"
                uses: "danharrin/monorepo-split-github-action@v2.3.0"
                with:
                    package_directory: '${{ matrix.package.local_path }}'
                    repository_organization: 'crantron'
                    repository_name: '${{ matrix.package.split_repository }}'
                    user_name: "crantron"
                    user_email: "crantron@gmail.com"
                    github_token: ${{ secrets.PAT }}
            #with tag
            -
                if: "startsWith(github.ref, 'refs/tags/')"
                uses: "danharrin/monorepo-split-github-action@v2.3.0"
                with:
                    tag: ${GITHUB_REF#refs/tags/}
                    package_directory: '${{ matrix.package.local_path }}'
                    repository_organization: 'crantron'
                    repository_name: '${{ matrix.package.split_repository }}'
                    user_name: "crantron"
                    user_email: "crantron@gmail.com"
                    github_token: ${{ secrets.PAT }}
        
              
