name: 'Test Monorepo package split'

on: 
    push:
        branches:
            - main
        tags:
            - "*"
env:
    PAT: ${{ secrets.PAT }}
jobs: 
    packages_split:
      runs-on: ubuntu-latest

      strategy:
        fail-fast: false
        matrix:
            package:
                    - local_path: 'global/src/mono-repo-package'
                      split_repository: 'mono-repo-package'
                    - local_path: 'apps/src/commerce-emea'
                      split_repository: 'commerce-emea'
                    - local_path: 'apps/src/commerce-rs'
                      split_repository: 'commerce-rs'
                    - local_path: 'region/src/commerce-emea-bundle'
                      split_repository: 'commerce-emea-bundle'
                    - local_path: 'region/src/commerce-rs-bundle'
                      split_repository: 'commerce-rs-bundle'
                      

      steps:
            -   uses: actions/checkout@v3
            #no tag
            -
                if: "!startsWith(github.ref, 'refs/tags/')"
                uses: "danharrin/monorepo-split-github-action@v2.3.0"
                with:
                    package_directory: '${{ matrix.package.local_path }}'
                    repository_organization: 'crantron'
                    repository_name: '${{ matrix.package.split_repository }}'
                    user_name: "crantron"
                    user_email: "crantron@gmail.com"
            #with tag
            -
                if: "startsWith(github.ref, 'refs/tags/')"
                uses: "danharrin/monorepo-split-github-action@v2.3.0"
                with:
                    package_directory: '${{ matrix.package.local_path }}'
                    repository_organization: 'crantron'
                    repository_name: '${{ matrix.package.split_repository }}'
                    user_name: "crantron"
                    user_email: "crantron@gmail.com"
        
              
