name: 'Test Monorepo package split'

on: 
    push:
        branches:
            - main
env:
    PAT: ${{ secrets.PAT }}
jobs: 
    packages_split:
      runs-on: ubuntu-latest

      strategy:
        fail-fast: false
        matrix:
            package:
                    - local_path: 'mono-repo-package'
                      split_repository: 'mono-repo-package'
                    - local_path: 'commerce-emea'
                      split_repository: 'commerce-emea'
                    - local_path: 'commerce-rs'
                      split_repository: 'commerce-rs'

      steps:
            -   uses: actions/checkout@v3
            -
                uses: "danharrin/monorepo-split-github-action@v2.3.0"
                with:
                    package_directory: 'packages/${{ matrix.package.local_path }}'
                    repository_organization: 'crantron'
                    repository_name: '${{ matrix.package.split_repository }}'
                    user_name: "crantron"
                    user_email: "crantron@gmail.com"
        
              
